name = "RobustNMF"
uuid = "c8698dc1-cf29-40e8-b6d2-b408f1d58cd2"
authors = ["Adrian Brag <a.brag@campus.tu-berlin.de>", "Haitham Samaan <h.samaan@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Random = "1.11.0"
julia = "1.11"
